pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: /:year/:month/:title/
url: http://www.thomasleeper.com
author: Thomas J. Leeper
name: Thomas J. Leeper
description: open science, academia, and politics
gems:
 - jekyll-feed
